### ISSUE TITLE
Node 12 is deprecated and will stop working in the future

### ISSUE THREAD

**Issue by reconman** [rbialon/flake8-annotations#8]
When I run the action, I'm getting warnings about Node 12 being deprecated: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Seems easy to fix, just update the node version in action.yml to 16.

**Comment by rbialon** [comment]
Thank you for pointing this out @reconman !

**Comment by reconman** [comment]
I think you need to release a new version (v1.1 or v2) to have an effect.

**Comment by rbialon** [comment]
Once again thank you, haven't run through this procedure for some time. v1.1 is released on Martketplace

**Comment by reconman** [comment]
Seems like best practice is to retag the major version on every release.

So:
- Create a tag v1.0 from tag v1
- Replace tag v1 with the same commit as v1.1

**Comment by rbialon** [comment]
Good catch! And done, v1 now points to the v1.1 release 👍
